nome=input('Digite o nome do cliente:')
dia_vencimento=input('Digite o dia do vencimento:')
mes_vencimento=input('Digite o mês do vencimento:')
valor=input('Digite o valor da fatura:')
print(f'Olá, {nome}')
print(f'A sua fatura com vencimento em {dia_vencimento} de {mes_vencimento} no valor de R$ {valor} está fechada.')